server:
  port: 8082
  shutdown: graceful
  netty:
    connection-timeout: 3s
    idle-timeout: 20s

spring:
  application:
    name: orders-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/orders_service_db
    pool:
      max-create-connection-time: 2s
      initial-size: 6
      max-size: 12
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/orders_service_db
  config:
    import: ${configserver.import}
  cloud:
    config:
      import-check:
        enabled: false
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      label: master

eureka:
  client:
    service-url:
      defaultZone: ${external.service-discovery-url}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true

configserver:
  import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8085}

external:
  service-discovery-url: http://localhost:8761/eureka/
  product-service-url: http://localhost:8081
  product-info-path: "/v1/products/product-info"
