server:
  port: 8082
  shutdown: graceful
  netty:
    connection-timeout: 3s
    idle-timeout: 20s

spring:
  application:
    name: orders-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/orders_service_db
    pool:
      max-create-connection-time: 2s
      initial-size: 6
      max-size: 12
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/orders_service_db
  config:
    import: ${configserver.import}
  cloud:
    config:
      import-check:
        enabled: false
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      label: master

eureka:
  client:
    service-url:
      defaultZone: ${external.service-discovery-url}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true

configserver:
  import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8085}

external:
  service-discovery-url: http://localhost:8761/eureka/
  product-service-url: http://product-service
  product-info-path: "/v1/products/product-info"
  default-timeout: 2s
  retry-backoff: 100ms
  retry-count: 5
  retry-jitter: 0.75

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  submit-order:
    summary: Создание заказа пользователем.
    description: |
      Создает новый заказ на имя пользователя. 
      Названия товаров передаются в теле запроса. 
      В случае отсутствия какого-либо товара в Product Service, возвращается ошибка 404.
  get-orders:
    summary: Получение списка заказов пользователя.
    description: Возвращает список заказов пользователя, отсортированный по дате создания заказа.
  response:
    submitOk: Заказ успешно сформирован.
    submitBadRequest: Заказ не был сформирован из-за ошибки в запросе. Подробнее в сообщении об ошибке.
    submitNotFound: Заказ не был сформирован, так как часть товаров отсутствует.
    submitInternalError: Заказ не был сформирован из-за ошибки на сервере. Подробнее в сообщении об ошибке.
    getOk: Список заказов пользователя сформирован.
    getBadRequest: Не удалось сформировать список заказов пользователя из-за ошибки в параметрах запроса.
